### ISSUE TITLE
设定FlowLayout子元素的gravity属性

### ISSUE THREAD

**Issue by demonyan** [hongyangAndroid/FlowLayout#10]
>看到豆瓣App的flowlayout子元素居中挺漂亮的哈！等下提交一个PR
![flowlayout](https://cloud.githubusercontent.com/assets/6286833/11140374/93ac7fa6-8a14-11e5-8277-0a87b6a0fb74.png)

**Comment by VolleyCN** [comment]
来信已经收到。在你那学到很多东西。大神在哪工作呢？ 发自网易邮箱大师 在2015年11月13日 15:06 ，张鸿洋写道： Closed #10 via #11. — Reply to this email directly or view it on GitHub.
