### ISSUE TITLE
adapter无法重新数据，删除一项都不行

### ISSUE THREAD

**Issue by weituotian** [hongyangAndroid/FlowLayout#105]
我想删除一项都不行，adapter无法重新设置列表的数据。

**Comment by weituotian** [comment]
根本没有方法

**Comment by hongyangAndroid** [comment]
可以在构造方法时，传入一个List集合（可以为size=0的集合）。
外部可以一直操作这个集合，保持该集合引用指向的对象不变（更新数据使用clear，addAll），这样可以操作完就notifyDataChanged()。
