### ISSUE TITLE
其实大家可以不用这个库了，官方的RecyclerView已经支持流式布局了，设置一个FlexboxLayoutManager就行了

### ISSUE THREAD

**Issue by shlockfan** [hongyangAndroid/FlowLayout#122]
FlexboxLayoutManager layoutManager = new FlexboxLayoutManager(context);
layoutManager.setFlexWrap(FlexWrap.WRAP);
layoutManager.setAlignItems(AlignItems.STRETCH);
rvMain.setLayoutManager(layoutManager);
就这样，就可以支持各种tag的布局了

**Comment by luoxinwu** [comment]
谢谢老哥。

**Comment by docwei2050** [comment]
for (int i = 0; i < adapter.getCount(); i++) {
            // 其实并不知道要子View是什么，这里就仿照baseAdapter来写
            View tagView = adapter.getView(this, i, adapter.getItem(i));

            tagViewContainer = new TagView(getContext());
            tagView.setDuplicateParentStateEnabled(true);
            if (tagView.getLayoutParams() != null) {
                tagViewContainer.setLayoutParams(tagView.getLayoutParams());


            }

**Comment by shlockfan** [comment]
@fish-ball 我一直用没什么问题，而且用的recyclerView，加载大量tag也无压力。
