### ISSUE TITLE
ListView中使用Flowlayoout如何解决复用问题

### ISSUE THREAD

**Issue by hulegithub** [hongyangAndroid/FlowLayout#18]
我在listview中item布局中使用了Flowlayoout，因为有复用，发现每次滑动Listview选中的标签状态会发生很乱的情况，不知道如何解决，请大神指点，不胜感激！

**Comment by CaMnter** [comment]
@hulegithub 复用的convertView，每次都先remove全部childView，再Add当前item需要的childView

**Comment by hulegithub** [comment]
谢谢，我已经解决

**Comment by CaMnter** [comment]
@hulegithub  可以 close 此 issue 了 :)
