### ISSUE TITLE
Listview中无法使用TagFlowLayout

### ISSUE THREAD

**Issue by hulegithub** [hongyangAndroid/FlowLayout#19]
我后来发现在Listview中使用TagFlowLayout，不复用也会有问题，每次滑动的时候之前选择的状态丢失，试了很多方法都没有完美解决，求指导，谢谢！

**Comment by LL101SS** [comment]
@hongyangAndroid  遇到同样的问题，能不能说下解决办法，谢谢

**Comment by hulegithub** [comment]
你需要在你的Adapter中通过监听Flowlayout.setOnSelectListener()来实现，再通过tagAdapter.setSelectedList(int[])来解决

**Comment by LL101SS** [comment]
@hulegithub @hongyangAndroid  刚试了下，你这种方式ListView中不行，滑动后选择状态丢失，不滑动选中之后就不能取消了

**Comment by hulegithub** [comment]
你监听的时候，先清除状态

**Comment by hongyangAndroid** [comment]
ok，已经添加了listview的例子。

**Comment by LL101SS** [comment]
@hongyangAndroid  我选中的A，再滑回来，选中的变成其他的了，一直在变

**Comment by hongyangAndroid** [comment]
@LL101SS 已修复。
