### ISSUE TITLE
TagAdapter 隐藏Bug

### ISSUE THREAD

**Issue by anenn** [hongyangAndroid/FlowLayout#27]
public void setSelectedList(int... pos)
    {
        for (int i = 0; i < pos.length; i++)
            mCheckedPosList.add(pos[i]);
        notifyDataChanged();
    }

    public void setSelectedList(Set<Integer> set)
    {
        mCheckedPosList.clear();
        mCheckedPosList.addAll(set);
        notifyDataChanged();
    }

针对 public void setSelectedList(int... pos) 方法里前面最好也添加一句 mCheckedPosList.clear();

**Comment by hongyangAndroid** [comment]
thx~多谢提醒
