### ISSUE TITLE
似乎你并没有处理multi_suppout=false的情况

### ISSUE THREAD

**Issue by gundumw100** [hongyangAndroid/FlowLayout#3]
如果要实现Radiobutton的效果呢？
是不是应该将multi_suppout置成false？
但是实际并没效果。
也许我用错了？

**Comment by hongyangAndroid** [comment]
max_select设置为1即可。

**Comment by gundumw100** [comment]
将max_select设置为1并不能解决问题，因为它失去切换到下一个选中项了

**Comment by gundumw100** [comment]
我添加了一段代码，用于解决这个问题
你看看是否合理;

public TagFlowLayout(Context context, AttributeSet attrs, int defStyle)
    {
        super(context, attrs, defStyle);
        TypedArray ta = context.obtainStyledAttributes(attrs, R.styleable.TagFlowLayout);
        mSupportMulSelected = ta.getBoolean(R.styleable.TagFlowLayout_multi_suppout, true);
        mSelectedMax = ta.getInt(R.styleable.TagFlowLayout_max_select, -1);
        ta.recycle();

//        if (mSupportMulSelected)//delete it
//        {
            setClickable(true);
//        }
    }

private int oldPosition=-1;
    private void doSelect(TagView child, int position)
    {
        if (mSupportMulSelected)
        {
           //yours
        }else{
        	if (!child.isChecked()){
        		if(oldPosition>=0){
        			((TagView)getChildAt(oldPosition)).setChecked(false);
        		}
        		child.setChecked(true);
        		mSelectedView.clear();
                mSelectedView.add(position);
                oldPosition=position;
        	}else{
        		child.setChecked(false);
        		mSelectedView.clear();
        	}
        	 if (mOnSelectListener != null)
             {
                 mOnSelectListener.onSelected(new HashSet<Integer>(mSelectedView));
             }
        }
    }

**Comment by hongyangAndroid** [comment]
多谢，已经添加你所描述的功能，欢迎提意见。
