### ISSUE TITLE
在onTagClick方法中如果传回来一个当前tagView是否被选中的布尔值也许会带来更多的便利

### ISSUE THREAD

**Issue by BrickWorkerKing** [hongyangAndroid/FlowLayout#30]
经过一番使用之后，发现无法在外面获取tagView的选中状态，也许是我自己没有找到获取的方法。然后试着在onTagClick加了个选中状态的返回参数，对于我当前的需要来说更加便利。在您这学到很多，非常感谢！

**Comment by houxiaodong** [comment]
这个问题你解决咯吗？我这边也有同样的需求？
