### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by gundumw100** [hongyangAndroid/FlowLayout#4]
为什么要在点击Tag的时候使用for循环查找点击了哪个TagView？
既然用了Adapter模式，最好实现OnItemClickListener取代setOnTagClickListener，不要使用findChild(int x, int y)去查找点了哪个Item，
应该在addView(tagView)之前实现一个tagView.addOnClickListener(...)取代它。

**Comment by hongyangAndroid** [comment]
感谢提问，首先我不认为这是个性能问题，即使是为单个View去设置onClickListener，系统在找子View的时候，依然是for循环+坐标判断；类似ListView这样的Adapter模式，也不会为每个View去设置onClickListener。

**Comment by gundumw100** [comment]
我改了一下这个问题，在下面的代码中增加了tagViewContainer.setOnClickListener()：
把你原来的performClick()，onTouchEvent(MotionEvent event)，findPosByView(View child)，findChild(int x, int y)全都注释掉了，至少目前没问题。
我敢肯定，效率会增加不少，代码还少了很多。
private void changeAdapter()
    {
        removeAllViews();
        TagAdapter adapter = mTagAdapter;
        TagView tagViewContainer = null;

        for (int i = 0; i < adapter.getCount(); i++)
        {
            View tagView = adapter.getView(this, i, adapter.getItem(i));
            tagViewContainer = new TagView(getContext());
            tagView.setDuplicateParentStateEnabled(true);
            tagViewContainer.setLayoutParams(tagView.getLayoutParams());
            tagViewContainer.addView(tagView);
            final int pos=i;
            tagViewContainer.setOnClickListener(new View.OnClickListener() {
				
				@Override
				public void onClick(View view) {
					// TODO Auto-generated method stub
					doSelect((TagView)view, pos);
					if (mOnTagClickListener != null)
					{
						mOnTagClickListener.onTagClick(view, pos, TagFlowLayout.this);
					}
					
				}
			});
            addView(tagViewContainer);
        }

    }

**Comment by hongyangAndroid** [comment]
恩，依旧是感谢提出。虽然我不喜欢这种写法~

**Comment by gundumw100** [comment]
哦,你就是张鸿洋啊，我没留意，失敬失敬

**Comment by hongyangAndroid** [comment]
哈，惭愧，多谢指点。

**Comment by tankcong** [comment]
我也有疑问。。@鸿洋，您用layout自身来处理click事件而不是交由Tag自身处理这样的考虑出发点在哪？个人习惯还是有什么额外的考虑？我自己考虑的时候第一反应是子view自己处理，就想@gundumw100的解决方案那样。
