### ISSUE TITLE
在设置TagFlowLayout.OnSelectListener后没有触发

### ISSUE THREAD

**Issue by skymxc** [hongyangAndroid/FlowLayout#71]
@hongyangAndroid 我在设置了事件后，并没有触发，两个事件都没有触发

这是我的代码

    private TagFlowLayout.OnSelectListener onYHGSelectLis = new TagFlowLayout.OnSelectListener() {
        @Override
        public void onSelected(Set<Integer> selectPosSet) {
            log("onSelected", "selectSet="+selectPosSet.toString());
        }
    };

    private TagFlowLayout.OnTagClickListener onYHGClickLis = new TagFlowLayout.OnTagClickListener() {
        @Override
        public boolean onTagClick(View view, int position, FlowLayout parent) {
            log("onTagClick", "posistion="+position);
            return true;
        }
    };

设置了事件

        tagFlowLayout.setOnSelectListener(onYHGSelectLis);
        tagFlowLayout.setOnTagClickListener(onYHGClickLis);

我看了一下您的源码，这两个事件都是在performClick()方法中调用的。

TagFlowLayout中的performClick()方法 是在什么情况下才会触发。我查了一下这个方法 这个是模拟点击事件。

您是在哪个地方调用的这个方法呢。希望指教一下。

    @Override
    public boolean performClick()
    {
        if (mMotionEvent == null) return super.performClick();

        int x = (int) mMotionEvent.getX();
        int y = (int) mMotionEvent.getY();
        mMotionEvent = null;

        TagView child = findChild(x, y);
        int pos = findPosByView(child);
        if (child != null)
        {
            doSelect(child, pos);
            if (mOnTagClickListener != null)
            {
                return mOnTagClickListener.onTagClick(child.getTagView(), pos, this);
            }
        }
        return true;
    }

thanks

**Comment by sky-mxc** [comment]
performClick() 会由系统调用，为什么我的这边没有触发呢

**Comment by sky-mxc** [comment]
我重写了 onInterceptTouchEvent() 拦截了事件，让事件直接去 onTouchEvent(),这样就触发了 performClick()； 不然 子项会把事件消费掉，就不会回掉父控件的 onTouchEvent();
